config/routes.rb
Rails.application.routes.draw do
  root 'pictures#index'

  resources :pictures

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	scope :newest_first, -> {order("created_at DESC")}
	scope :most_recent_five, -> { newest_first.limit(5) }
	scope :created_before, ->(time) { where("created_at < ?", time) } # Always use escaped query syntax
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
	def index
		@most_recent_pictures = Picture.most_recent_five
		@older_pictures = Picture.created_before(0.day.ago)
	end

	def show
		@picture = Picture.find(params[:id].to_i)
	end

	def edit
		@picture = Picture.find(params[:id].to_i)
	end

	def update
		@picture = Picture.find(params[:id].to_i)
		if @picture.update_attributes(picture_params)
			redirect_to "/pictures/#{@picture.id}"
		else
			render :edit
		end
	end

	def delete
		@picture = Picture.find(params[:id].to_i)
		@picture.destroy
		redirect_to pictures_url
	end

	def new
		@picture = Picture.new
	end

	def create
		@picture = Picture.new(picture_params)
		if @picture.save
			redirect_to pictures_url
		else
			render :new
		end
	end

	private
	def picture_params
		params.require(:picture).permit(:artist, :title, :url)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Photogur2</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<link href='http://fonts.googleapis.com/css?family=Lobster|Open+Sans|Yanone+Kaffeesatz|Maven+Pro|Pacifico|Dancing+Script|Sacramento' rel='stylesheet' type='text/css'>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<%= yield %>

</body>
</html>

app/views/pictures/edit.html.erb
<h1>Edit Pictures</h1>
<p><%= link_to "Back" , @picture %></p>

<%= form_for @picture do |f|%>
	<p>
		<%= f.label "artist" %><br>
		<%= f.text_field "artist" %>
	</p>
	<p>
		<%= f.label "title" %><br>
		<%= f.text_field "title" %>
	</p>
	<p>
		<%= f.label "url" %><br>
		<%= f.text_field "url" %>
	</p>
	<p>
		<%= submit_tag "Save" %>
	</p>
<% end %>

app/views/pictures/index.html.erb
<h1>photogur</h1><br>
<%= link_to "Add a Picture!", new_picture_url %>

<% @most_recent_pictures.each do |picture| %>
	<p><%= link_to image_tag(picture.url), "/pictures/#{picture.id}" %>
	<p><%= picture.title %>, <%= picture.artist %></p>
	<br><br>
<% end %>

<h2>Older Posts</h2>
<p>Total: <%= @older_pictures.count %></p>
<% @older_pictures.each do |picture| %>
	<p><%= link_to "#{picture.title}", "/pictures/#{picture.id}" %></p>
<% end %>

app/views/pictures/new.html.erb
<h1>Add a Picture</h1>
<%= link_to "Back to Pictures", pictures_url %>   <!-- pictures_url is the same as /pictures-->

<%= form_for @picture do |f| %>
  <p>
    <%= f.label "artist" %><br>
    <%= f.text_field "artist" %>
  </p>
  <p>
    <%= f.label "title" %><br>
    <%= f.text_field "title" %>
  </p>
  <p>
    <%= f.label "url" %><br>
    <%= f.text_field "url" %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/pictures/show.html.erb
<h1><%= @picture.title %>, <%= @picture.artist %></h2><br>

<%= image_tag @picture.url %><br>

<%= link_to "Back to Pictures" , pictures_url %> | <%= link_to "Edit", edit_picture_url %> | <%= link_to "Delete", @picture, method: :delete, data: {confirm: "Are you sure you want to delete this picture?"}  %>